{% set version = "0.4.0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-qgisprocess
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/qgisprocess_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/qgisprocess/qgisprocess_{{ version }}.tar.gz
  sha256: 0b86faff81e83f940b3c600355794a3e54f316d01eb4d033ca9c260b9d775037

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-assertthat
    - r-glue
    - r-jsonlite
    - r-processx >=3.5.2
    - r-rappdirs
    - r-rlang
    - r-stringr
    - r-tibble
    - r-vctrs
    - r-withr

  run:
    - r-base
    - r-assertthat
    - r-glue
    - r-jsonlite
    - r-processx >=3.5.2
    - r-rappdirs
    - r-rlang
    - r-stringr
    - r-tibble
    - r-vctrs
    - r-withr
    - qgis >=3.28

test:
  requires:
    - r-testthat
    - r-raster
    - r-rgdal
    - r-sf
    - r-stars
    - r-terra
    # Following CDTs are from `qgis` feedstock test section
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('alsa-lib-devel') }}        # [linux]
    - {{ cdt('gtk2-devel') }}            # [linux]
    - {{ cdt('gtkmm24-devel') }}         # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxcb') }}                # [linux]
  source_files:
    - tests/
  commands:
    #- qgis_process --help
    - $R -e "library('qgisprocess')"                                         # [not win]
    - $R -e "testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)"  # [not win]
    - "\"%R%\" -e \"library('qgisprocess')\""                                         # [win]
    - "\"%R%\" -e \"testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)\""  # [win]

about:
  home: https://r-spatial.github.io/qgisprocess/
  dev_url: https://github.com/r-spatial/qgisprocess
  license: GPL-3.0-or-later
  summary: Provides seamless access to the 'QGIS' (<https://qgis.org/en/site/>) processing toolbox using the standalone 'qgis_process' command-line utility.  Both native and third-party (plugin) processing providers are supported.  Beside referring data sources from file, also common objects from 'sf', 'terra' and 'stars'
    are supported. The native processing algorithms are documented by QGIS.org (2023) <https://docs.qgis.org/latest/en/docs/user_manual/processing_algs/>.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# The original CRAN metadata for this package was:

# Package: qgisprocess
# Title: Use 'QGIS' Processing Algorithms
# Version: 0.1.0
# Authors@R: c( person("Dewey", "Dunnington", , "dewey@fishandwhistle.net", role = "aut", comment = c(ORCID = "0000-0002-9415-4582", affiliation = "Voltron Data")), person("Floris", "Vanderhaeghe", , "floris.vanderhaeghe@inbo.be", role = c("aut", "cre"), comment = c(ORCID = "0000-0002-6378-6229", affiliation = "Research Institute for Nature and Forest (INBO)")), person("Jan", "Caha", , "jan.caha@outlook.com", role = "aut", comment = c(ORCID = "0000-0003-0165-0606")), person("Jannes", "Muenchow", , "malnamalja@gmx.de", role = "aut", comment = c(ORCID = "0000-0001-7834-4717")), person("Antony", "Barja", , "antony.barja8@gmail.com", role = "ctb", comment = c(ORCID = "0000-0001-5921-2858")), person("Robin", "Lovelace", , "rob00x@gmail.com", role = "ctb", comment = c(ORCID = "0000-0001-5679-6536")), person("Jakub", "Nowosad", , "nowosad.jakub@gmail.com", role = "ctb", comment = c(ORCID = "0000-0002-1057-3721")), person("Research Institute for Nature and Forest (INBO)", role = c("cph", "fnd"), comment = "https://www.inbo.be/en/") )
# Description: Provides seamless access to the 'QGIS' (<https://qgis.org/en/site/>) processing toolbox using the standalone 'qgis_process' command-line utility.  Both native and third-party (plugin) processing providers are supported.  Beside referring data sources from file, also common objects from 'sf', 'terra' and 'stars' are supported. The native processing algorithms are documented by QGIS.org (2023) <https://docs.qgis.org/latest/en/docs/user_manual/processing_algs/>.
# License: GPL (>= 3)
# URL: https://r-spatial.github.io/qgisprocess/, https://github.com/r-spatial/qgisprocess
# BugReports: https://github.com/r-spatial/qgisprocess/issues
# Depends: R (>= 3.6.0)
# Imports: assertthat, glue, jsonlite, processx (>= 3.5.2), rappdirs, rlang, stats, stringr, tibble, vctrs, withr
# Suggests: dplyr, knitr, mapview, raster, rmarkdown, rprojroot, sf, spDataLarge, stars, stringi, terra, testthat, tidyr
# VignetteBuilder: knitr
# Additional_repositories: https://geocompr.r-universe.dev
# Config/checklist/communities: inbo
# Config/checklist/keywords: R; package; QGIS
# Encoding: UTF-8
# Language: en-GB
# RoxygenNote: 7.2.3
# SystemRequirements: 'QGIS' latest or long-term release (>= 3.28). Older 'QGIS' releases are not officially supported, but may work since 'QGIS' 3.16.
# NeedsCompilation: no
# Packaged: 2023-08-17 09:25:05 UTC; floris
# Author: Dewey Dunnington [aut] (<https://orcid.org/0000-0002-9415-4582>, Voltron Data), Floris Vanderhaeghe [aut, cre] (<https://orcid.org/0000-0002-6378-6229>, Research Institute for Nature and Forest (INBO)), Jan Caha [aut] (<https://orcid.org/0000-0003-0165-0606>), Jannes Muenchow [aut] (<https://orcid.org/0000-0001-7834-4717>), Antony Barja [ctb] (<https://orcid.org/0000-0001-5921-2858>), Robin Lovelace [ctb] (<https://orcid.org/0000-0001-5679-6536>), Jakub Nowosad [ctb] (<https://orcid.org/0000-0002-1057-3721>), Research Institute for Nature and Forest (INBO) [cph, fnd] (https://www.inbo.be/en/)
# Maintainer: Floris Vanderhaeghe <floris.vanderhaeghe@inbo.be>
# Repository: CRAN
# Date/Publication: 2023-08-17 15:10:02 UTC

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
